#hyprpaper - wallpaper config
#preload = /home/ofirsinn/.config/themes/current/wallpapers/catpuccin_3.png
wallpaper {
	monitor = 
	path = /home/ofirsinn/.config/themes/current/wallpapers/catpuccin_3.png
	fit_mode = cover 
}

splash = false
