set -g @active_tab_foreground "#CDD6F4"
set -g @active_tab_background "#1E1E2E"
set -g @inactive_tab_foreground "#6C7086"
set -g @inactive_tab_background "#11111B"
set -g @tab_bar_background "#181825"

